# Generated by Django 6.0.5 on 2026-05-23 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0013_messagereaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('owner_account_number', models.CharField(db_index=True, max_length=10)),
                ('client_story_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('visibility', models.CharField(choices=[('all_contacts', 'All contacts'), ('specific_contacts', 'Specific contacts')], default='all_contacts', max_length=30)),
                ('expiry_hours', models.PositiveSmallIntegerField(choices=[(6, '6 hours'), (12, '12 hours'), (24, '24 hours')], default=24)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('payload_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner_user_id', 'created_at'], name='stories_sto_owner_u_178323_idx'), models.Index(fields=['owner_user_id', 'expires_at'], name='stories_sto_owner_u_cda2fd_idx'), models.Index(fields=['owner_account_number', 'expires_at'], name='stories_sto_owner_a_79d1df_idx'), models.Index(fields=['status', 'expires_at'], name='stories_sto_status_89085b_idx'), models.Index(fields=['visibility', 'status'], name='stories_sto_visibil_5f1151_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_story_id', ''), _negated=True), fields=('owner_user_id', 'client_story_id'), name='uq_story_owner_client_story_id'), models.CheckConstraint(condition=models.Q(('expiry_hours__in', [6, 12, 24])), name='ck_story_expiry_hours_allowed')],
            },
        ),
        migrations.CreateModel(
            name='StoryUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('owner_account_number', models.CharField(db_index=True, max_length=10)),
                ('client_story_id', models.CharField(db_index=True, max_length=120)),
                ('media_client_id', models.CharField(blank=True, max_length=255)),
                ('media_index', models.PositiveIntegerField(default=0)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('original_mime_type', models.CharField(blank=True, max_length=120)),
                ('original_file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('encrypted_file_size_bytes', models.PositiveBigIntegerField()),
                ('cloudinary_public_id', models.CharField(max_length=512, unique=True)),
                ('cloudinary_asset_id', models.CharField(blank=True, max_length=255)),
                ('cloudinary_resource_type', models.CharField(default='raw', max_length=40)),
                ('cloudinary_folder', models.CharField(max_length=255)),
                ('secure_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('completed', 'Completed'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='issued', max_length=20)),
                ('signature_timestamp', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['owner_user_id', 'client_story_id', 'status'], name='stories_sto_owner_u_fcaa91_idx'), models.Index(fields=['owner_account_number', 'status'], name='stories_sto_owner_a_436ff7_idx'), models.Index(fields=['status', 'expires_at'], name='stories_sto_status_8d7804_idx'), models.Index(fields=['media_type', 'status'], name='stories_sto_media_t_1ca513_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('viewer_account_number', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='stories.story')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['viewer_user_id', 'created_at'], name='stories_sto_viewer__ff8003_idx'), models.Index(fields=['viewer_account_number', 'created_at'], name='stories_sto_viewer__1d7ab4_idx'), models.Index(fields=['story', 'created_at'], name='stories_sto_story_i_41e6a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('story', 'viewer_user_id'), name='uq_story_audience_viewer')],
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('viewer_account_number', models.CharField(db_index=True, max_length=10)),
                ('reaction', models.CharField(choices=[('thumbs_up', 'Thumbs up'), ('heart', 'Heart'), ('laugh', 'Laugh'), ('surprised', 'Surprised'), ('sad', 'Sad')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_reactions', to='messaging.message')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='stories.story')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['story', 'reaction'], name='stories_sto_story_i_682ac3_idx'), models.Index(fields=['viewer_user_id', 'updated_at'], name='stories_sto_viewer__a13d8f_idx'), models.Index(fields=['viewer_account_number', 'updated_at'], name='stories_sto_viewer__097ec0_idx'), models.Index(fields=['message'], name='stories_sto_message_af3f43_idx')],
                'constraints': [models.UniqueConstraint(fields=('story', 'viewer_user_id'), name='uq_story_reaction_viewer')],
            },
        ),
        migrations.CreateModel(
            name='StoryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('viewer_account_number', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_replies', to='messaging.message')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stories.story')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['story', 'created_at'], name='stories_sto_story_i_ebf4aa_idx'), models.Index(fields=['viewer_user_id', 'created_at'], name='stories_sto_viewer__b29d03_idx'), models.Index(fields=['viewer_account_number', 'created_at'], name='stories_sto_viewer__7c15bc_idx'), models.Index(fields=['message'], name='stories_sto_message_ff3c4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('encrypted_file_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('encrypted_file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=512)),
                ('cloudinary_asset_id', models.CharField(blank=True, max_length=255)),
                ('cloudinary_resource_type', models.CharField(blank=True, max_length=40)),
                ('cloudinary_folder', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='stories.story')),
                ('upload_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='stories.storyuploadintent')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['story', 'sort_order'], name='stories_sto_story_i_08761c_idx'), models.Index(fields=['media_type'], name='stories_sto_media_t_c22d5f_idx'), models.Index(fields=['cloudinary_public_id'], name='stories_sto_cloudin_bd03df_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('viewer_account_number', models.CharField(db_index=True, max_length=10)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story')),
            ],
            options={
                'ordering': ['viewed_at', 'id'],
                'indexes': [models.Index(fields=['story', 'viewed_at'], name='stories_sto_story_i_0063d4_idx'), models.Index(fields=['viewer_user_id', 'viewed_at'], name='stories_sto_viewer__f4f57b_idx'), models.Index(fields=['viewer_account_number', 'viewed_at'], name='stories_sto_viewer__0d0bcc_idx')],
                'constraints': [models.UniqueConstraint(fields=('story', 'viewer_user_id'), name='uq_story_view_viewer')],
            },
        ),
    ]
