# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.PositiveBigIntegerField(unique=True)),
                ('owner_account_number', models.CharField(db_index=True, max_length=10)),
                ('expiry_hours', models.PositiveSmallIntegerField(choices=[(6, '6 hours'), (12, '12 hours'), (24, '24 hours')], default=24)),
                ('visibility', models.CharField(choices=[('all_contacts', 'All contacts'), ('specific_contacts', 'Specific contacts')], default='all_contacts', max_length=30)),
                ('audience_account_numbers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['owner_account_number'], name='stories_sto_owner_a_b1f83d_idx'), models.Index(fields=['visibility', 'updated_at'], name='stories_sto_visibil_1a43d0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expiry_hours__in', [6, 12, 24])), name='ck_story_settings_expiry_hours_allowed')],
            },
        ),
    ]
