# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('media', 'Media'), ('text', 'Text')], default='media', max_length=20),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['story_type', 'status'], name='stories_sto_story_t_357549_idx'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.CheckConstraint(condition=models.Q(('story_type__in', ['media', 'text'])), name='ck_story_type_allowed'),
        ),
    ]
