# Generated by Django 6.0.5 on 2026-05-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_story_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='story',
            new_name='stories_sto_story_t_357549_idx',
            old_name='stories_sto_story__6b39a4_idx',
        ),
    ]
