# Generated by Django 6.0.5 on 2026-06-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_storyview_hidden_from_owner'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storyview',
            new_name='stories_sto_story_i_ee2e74_idx',
            old_name='stories_sto_story_i_ghost_idx',
        ),
    ]
