# Generated by Django 6.0.5 on 2026-05-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], db_index=True, default='direct', max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('created_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['room_type', 'updated_at'], name='messaging_r_room_ty_bdaf08_idx'), models.Index(fields=['created_by_user_id'], name='messaging_r_created_a8ed7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_user_id', models.PositiveBigIntegerField()),
                ('recipient_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('client_message_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.room')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='messaging_m_room_id_689271_idx'), models.Index(fields=['sender_user_id', 'created_at'], name='messaging_m_sender__0873a3_idx'), models.Index(fields=['recipient_user_id', 'created_at'], name='messaging_m_recipie_61083b_idx'), models.Index(fields=['status'], name='messaging_m_status_7d189b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_message_id', ''), _negated=True), fields=('sender_user_id', 'client_message_id'), name='uq_sender_client_message_id')],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('account_number', models.CharField(blank=True, max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.room')),
            ],
            options={
                'ordering': ['joined_at', 'id'],
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='messaging_r_user_id_0d3153_idx'), models.Index(fields=['room', 'is_active'], name='messaging_r_room_id_9f005c_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'user_id'), name='uq_room_participant_user')],
            },
        ),
    ]
