# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messageattachment_message_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
