# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_delivery_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_while_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
