# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_sent_while_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='cloudinary_asset_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='cloudinary_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='cloudinary_resource_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
