# Generated by Django 6.0.5 on 2026-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='story_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
