from django.urls import path

from .views import (
    authorize_message,
    complete_crypto_file_upload_intent,
    create_crypto_file_upload_intents,
    crypto_key_backup,
    deliver_room,
    health_check,
    hide_presence_from_user,
    list_rooms,
    message_reaction,
    read_room,
    register_crypto_device,
    recipient_crypto_devices,
    refresh_presence_visibility_for_user,
    release_blocked_messages,
    revoke_crypto_device,
    room_messages,
    send_message,
    set_default_crypto_device,
    update_message_authorization_cache,
    update_presence_visibility_for_user,
    update_default_crypto_device_password,
    upload_crypto_file,
    user_crypto_devices,
)

urlpatterns = [
    path('health/', health_check, name='messenger-health'),
    path('presence/internal/hidden/', hide_presence_from_user, name='presence-hidden'),
    path('presence/internal/visibility/', update_presence_visibility_for_user, name='presence-visibility'),
    path('messages/internal/authorization-cache/', update_message_authorization_cache, name='message-authorization-cache'),
    path('presence/visibility/refresh/', refresh_presence_visibility_for_user, name='presence-visibility-refresh'),
    path('rooms/', list_rooms, name='room-list'),
    path('rooms/<int:room_id>/messages/', room_messages, name='room-messages'),
    path('rooms/<int:room_id>/delivered/', deliver_room, name='room-delivered'),
    path('rooms/<int:room_id>/read/', read_room, name='room-read'),
    path('rooms/<int:room_id>/blocked-messages/release/', release_blocked_messages, name='room-blocked-messages-release'),
    path('crypto/devices/', register_crypto_device, name='crypto-device-register'),
    path('crypto/devices/<str:device_id>/default/', set_default_crypto_device, name='crypto-device-default'),
    path('crypto/devices/default-password/', update_default_crypto_device_password, name='crypto-device-default-password-update'),
    path('crypto/devices/<str:device_id>/revoke/', revoke_crypto_device, name='crypto-device-revoke'),
    path('crypto/files/', upload_crypto_file, name='crypto-file-upload'),
    path('crypto/files/upload-intents/', create_crypto_file_upload_intents, name='crypto-file-upload-intent-create'),
    path('crypto/files/upload-intents/<uuid:upload_intent_id>/complete/', complete_crypto_file_upload_intent, name='crypto-file-upload-intent-complete'),
    path('crypto/key-backup/', crypto_key_backup, name='crypto-key-backup'),
    path('crypto/users/<int:user_id>/devices/', user_crypto_devices, name='crypto-user-devices'),
    path('crypto/recipients/<str:recipient_account_number>/devices/', recipient_crypto_devices, name='crypto-recipient-devices'),
    path('messages/authorize/', authorize_message, name='message-authorization'),
    path('messages/send/', send_message, name='message-send'),
    path('messages/<int:message_id>/reaction/', message_reaction, name='message-reaction'),
]
