# Generated by Django 6.0.5 on 2026-06-03 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_messaging', '0002_group_membership_roles'),
        ('messaging', '0014_message_story_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('text', models.TextField(blank=True)),
                ('client_message_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_replies', to='group_messaging.groupmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='messaging.room')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageEncryptedUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('sender_account_number', models.CharField(blank=True, max_length=10)),
                ('client_message_id', models.CharField(db_index=True, max_length=120)),
                ('attachment_client_id', models.CharField(blank=True, max_length=255)),
                ('attachment_index', models.PositiveIntegerField(default=0)),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('original_mime_type', models.CharField(blank=True, max_length=120)),
                ('original_file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('encrypted_file_size_bytes', models.PositiveBigIntegerField()),
                ('cloudinary_public_id', models.CharField(max_length=512, unique=True)),
                ('cloudinary_asset_id', models.CharField(blank=True, max_length=255)),
                ('cloudinary_resource_type', models.CharField(default='raw', max_length=40)),
                ('cloudinary_folder', models.CharField(max_length=255)),
                ('secure_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('completed', 'Completed'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='issued', max_length=20)),
                ('signature_timestamp', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_encrypted_upload_intents', to='messaging.room')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('reaction', models.CharField(choices=[('thumbs_up', 'Thumbs up'), ('heart', 'Heart'), ('laugh', 'Laugh'), ('surprised', 'Surprised'), ('sad', 'Sad')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='group_messaging.groupmessage')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='group_messaging.groupmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_receipts', to='messaging.room')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['room', 'created_at'], name='group_messa_room_id_f819d0_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['reply_to'], name='group_messa_reply_t_810e63_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['sender_user_id', 'created_at'], name='group_messa_sender__0c14ec_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['status'], name='group_messa_status_71a02b_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id', ''), _negated=True), fields=('sender_user_id', 'client_message_id'), name='uq_group_sender_client_message_id'),
        ),
        migrations.AddIndex(
            model_name='groupmessageencrypteduploadintent',
            index=models.Index(fields=['room', 'sender_user_id', 'client_message_id', 'status'], name='group_messa_room_id_d0bcd2_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessageencrypteduploadintent',
            index=models.Index(fields=['sender_user_id', 'status'], name='group_messa_sender__5457f6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessageencrypteduploadintent',
            index=models.Index(fields=['status', 'expires_at'], name='group_messa_status_376d63_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereaction',
            index=models.Index(fields=['message', 'reaction'], name='group_messa_message_99cf93_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereaction',
            index=models.Index(fields=['user_id', 'updated_at'], name='group_messa_user_id_ce21ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmessagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user_id'), name='uq_group_message_reaction_user'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereceipt',
            index=models.Index(fields=['room', 'user_id', 'read_at'], name='group_messa_room_id_82ec2c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereceipt',
            index=models.Index(fields=['room', 'user_id', 'delivered_at'], name='group_messa_room_id_39a6de_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereceipt',
            index=models.Index(fields=['message', 'delivered_at'], name='group_messa_message_25b23b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereceipt',
            index=models.Index(fields=['message', 'read_at'], name='group_messa_message_71d010_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmessagereceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user_id'), name='uq_group_message_receipt_user'),
        ),
    ]
